### ISSUE TITLE
Fix compatibility with SonarQube 6.x - ModuleFileSystem will be removed

### ISSUE THREAD

**Issue by henryju** [SonarQubeCommunity/sonar-css#261]
We'll remove ModuleFileSystem in SQ 6.0 so the CSS plugin will no more be compatible:
https://github.com/SonarQubeCommunity/sonar-css/blob/1.10/sonar-css-plugin/src/main/java/org/sonar/plugins/css/cpd/CssCpdMapping.java#L35

**Comment by racodond** [comment]
Thanks @henryju for the notification. I was seriously thinking about dropping this duplication detection feature from the CSS plugin because it doesn't bring that much value from my point of view on CSS code. What do you think? cc @kalidasya

**Comment by kalidasya** [comment]
@racodond if you say so, is that also true with cross project duplications? to be honest in the last few years I have not worked much with css projects, but what I can recall across applications I found a lot of duplications back then.
not sure what is the maintenance cost here, if you think it does not worth it (I guess there is no easy way to ask the "users"), we can drop it.

**Comment by racodond** [comment]
@kalidasya The issue about copy-paste detection in the CSS plugin is that it only detects exact copy-paste (that is quite rare). It would be nice to make the algorithm smarter. I created a ticket to think about it: https://github.com/SonarQubeCommunity/sonar-css/issues/262

Anyway, looking at it, the fix was quite simple: https://github.com/SonarQubeCommunity/sonar-css/commit/e63537cb38f1ac2254b4f29beaee20fd1094e72d

**Comment by kalidasya** [comment]
@racodond how can we improve the copy-paste detection? It was long ago but I thought we delegate it to the core and the plugin responsibility is the syntax tree creation

**Comment by racodond** [comment]
@kalidasya See https://github.com/SonarQubeCommunity/sonar-css/issues/262 description and let's continue the discussion there.

**Comment by henryju** [comment]
FYI the drop of ModuleFilesystem was delayed to 6.1 to give time to plugin to migrate:
https://jira.sonarsource.com/browse/SONAR-7864
